import dressShirtGreen from "./material/dress-shirts/dress-green.jpg";
import dressShirtRed from "./material/dress-shirts/dress-red.jpg";

import sweetShirtBlack from "./material/sweet-shirts/sweetShirt-black.jpg";
import sweetShirtRed from "./material/sweet-shirts/sweetShirt-red.jpg";
import sweetShirtRed2 from "./material/sweet-shirts/sweetShirt-red-2.jpg";
import sweetShirtYellow from "./material/sweet-shirts/sweetShirt-yellow.jpg";

import tankTopBlack from "./material/tank-top/tankTop-black.jpg";

import tShirtBlue from "./material/t-shirt/blue.jpg";
import tShirtRed from "./material/t-shirt/red.jpg";
import tShirtGreen from "./material/t-shirt/green.jpg";

const TEST_DATA = [
  {
    id: 1,
    type: "Dress Shirts",
    title: "Dress Shirts Red",
    img: dressShirtRed,
    thumbnail: [dressShirtRed, dressShirtRed, dressShirtRed],
    amount: 1,
    price: 119.99,
    sale: 89.99,
    size: ["s", "l"],
    color: ["red"],
    views: 3,
    dateTime: 1633816800000,
  },
  {
    id: 2,
    type: "Dress Shirts",
    title: "Dress Shirts green",
    img: dressShirtGreen,
    thumbnail: [dressShirtGreen, dressShirtGreen, dressShirtGreen],
    amount: 1,
    price: 119.99,
    size: ["s", "xxl"],
    color: ["green"],
    views: 5,
    dateTime: 1633730400000,
  },
  {
    id: 3,
    type: "Sweatshirts",
    title: "Sweat shirt black ",
    img: sweetShirtBlack,
    thumbnail: [sweetShirtBlack, sweetShirtBlack, sweetShirtBlack],
    amount: 1,
    price: 119.99,
    size: ["xs", "xl"],
    color: ["black"],
    views: 15,
    dateTime: 1633730400000,
  },
  {
    id: 4,
    type: "Sweatshirts",
    title: "Sweat shirt red ",
    img: sweetShirtRed,
    thumbnail: [sweetShirtRed, sweetShirtRed, sweetShirtRed],
    amount: 1,
    price: 119.99,
    size: ["xs", "xl"],
    color: ["red"],
    views: 15,
    dateTime: 1633730400000,
  },
  {
    id: 5,
    type: "Sweatshirts",
    title: "Sweat shirt red ",
    img: sweetShirtRed2,
    thumbnail: [sweetShirtRed2, sweetShirtRed2, sweetShirtRed2],
    amount: 1,
    price: 119.99,
    size: ["xs", "xxl"],
    color: ["red"],
    views: 15,
    dateTime: 1633730400000,
  },
  {
    id: 6,
    type: "Sweatshirts",
    title: "Sweat shirt yellow ",
    img: sweetShirtYellow,
    thumbnail: [sweetShirtYellow, sweetShirtYellow, sweetShirtYellow],
    amount: 1,
    price: 119.99,
    size: ["s", "l"],
    color: ["yellow"],
    views: 11,
    dateTime: 1633730400000,
  },

  {
    id: 8,
    type: "Tank Tops",
    title: "Tank Tops black",
    img: tankTopBlack,
    thumbnail: [tankTopBlack, tankTopBlack, tankTopBlack],
    amount: 1,
    price: 119.99,
    size: ["xs", "xl"],
    color: ["black"],
    views: 150,
    dateTime: 1633730400000,
  },
  {
    id: 9,
    type: "T-Shirts",
    title: "T-Shirt blue",
    img: tShirtBlue,
    thumbnail: [tShirtBlue, tShirtBlue, tShirtBlue],
    amount: 1,
    price: 119.99,
    size: ["xs", "xl"],
    color: ["blue"],
    views: 150,
    dateTime: 1633730400000,
  },
  {
    id: 10,
    type: "T-Shirts",
    title: "T-Shirt red",
    img: tShirtRed,
    thumbnail: [tShirtRed, tShirtRed, tShirtRed],
    amount: 1,
    price: 119.99,
    size: ["xs", "xl"],
    color: ["red"],
    views: 150,
    dateTime: 1633730400000,
  },
  {
    id: 11,
    type: "T-Shirts",
    title: "T-Shirt green",
    img: tShirtGreen,
    thumbnail: [tShirtGreen, tShirtGreen, tShirtGreen],
    amount: 1,
    price: 40,
    size: ["xs", "xl"],
    color: ["green"],
    views: 150,
    dateTime: 1633730400000,
  },
];

export default TEST_DATA;
